### ISSUE TITLE
Opal Deadlines

### ISSUE THREAD

**Issue by gorahul123** [Opal-Medical-Technologies/iCart-Electron-Desktop-App#2]
Opal Desktop Debriefs: SUNDAYS @1PM
Substantial Progress should be made for each debrief meeting, no hard deadlines

Tasks:
Rahul: Hardcoding middle section form w/ updating dummy buttons and text-entering blocks

Josh: Dynamically updating side bar from external json file

Runxuan: preview section hard-coded blank screen (no functuanality)

**Comment by runxuanjiang** [comment]
Outdated issue, closing.
