### ISSUE TITLE
Hub Tasks

### ISSUE THREAD

**Issue by gorahul123** [Opal-Medical-Technologies/iCart-Electron-Desktop-App#3]
Rahul:
-Complete MiddleBar, excluding kg toggle
-Move all textbox data onto one file DONE

Runxuan: 
-Complete skeleton of preview function ( the hard coded stuff)
-Work on dynamic updating of medCard (basically flutter)

Ameer:
-Work on checkboxes DONE

**Comment by runxuanjiang** [comment]
Completed.
