### ISSUE TITLE
Hub Deadlines Week 2

### ISSUE THREAD

**Issue by gorahul123** [Opal-Medical-Technologies/iCart-Electron-Desktop-App#4]
Runxuan:
-Start working on hardcoding test case and implementing variables into preview

Rahul and Ameer:
-Make function for bottom two checkboxes DONE
-Fix notes lines width DONE
-dynamic updating of Title meh
-MAKE SURE TO MAKE MIDDLE BAR SCROLLABLE IN THE WEEKEND

**Comment by runxuanjiang** [comment]
Completed.
