### ISSUE TITLE
TODO Thanksgiving Break

### ISSUE THREAD

**Issue by gorahul123** [Opal-Medical-Technologies/iCart-Electron-Desktop-App#7]
Runxuan:
-Change hardcoded version to variable inputs
-Test along each test case used in Opal App and screenshot each completed test case (add to folder to track progress)
**You can ignore the back side of the card for this week, also make sure variable names match last issue

Rahul:
-Test that every variable is changing as expected (textboxes and units)
-Modularize functions of MiddleBar, rather than having separate divs for each part
-Edit UI of Medication title so that it is as sleek as possible (no border when clicked, totally highlighted after one click, etc)
**you can do whatever you want with this part, just make the medTitle look intuitive

Ameer: 
-Scrolling Feature for middle bar

Josh:
-Make new file button that adds tab for new medication

**Comment by runxuanjiang** [comment]
We need to refactor some parts of the code to get rid of some of the code left behind from "create react app" and organize some other parts.

Also stop naming the commits the same thing.
